### ISSUE TITLE
设置元素的display为none打印不出来

### ISSUE THREAD

**Issue by n19ht** [Power-kxLee/vue-print-nb#114]
设置元素的display为none打印不出来，并且也设置了**打印前的回调**将元素的display设置为block

**Comment by dyywork** [comment]
vue-print-nb-dom-show可以试试这个

**Comment by n19ht** [comment]
> vue-print-nb-dom-show可以试试这个

谢谢，我改用了print-js

**Comment by firstblood93** [comment]
```css
@media print {
  #printMe{
   display:block;
  }
 }
```
